### PR TITLE
[Android] Handle `hover` events in `RNGestureHandlerRootHelper`

### LINKED ISSUE #3407: TalkBack cannot select UI elements after `Gesture.Pan()` triggers
### Description

After `Gesture.Pan()` is triggered. TalkBack will no longer be able to focus UI elements using the press-and-hold gesture. TalkBack is still able to select elements via the swipe-left and swipe-right gesture. This issue happens on both the new and old architecture.

https://github.com/user-attachments/assets/286c9bf9-1eac-4666-a981-b4793c58da19

### Steps to reproduce

Repro:

```tsx
import * as React from "react";
import { Button, Text, View } from "react-native";
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from "react-native-gesture-handler";

function useGesture() {
  return React.useMemo(() => {
    return Gesture.Pan();
  }, []);
}

export default function HomeScreen() {
  const gesture = useGesture();

  return (
    <GestureHandlerRootView>
      <GestureDetector gesture={gesture}>
        <View
          style={{ flex: 1, alignItems: "center", justifyContent: "center" }}
        >
          <Text>This is some selectable text.</Text>
          <Button title="And this is a button" />
        </View>
      </GestureDetector>
    </GestureHandlerRootView>
  );
}
```

1. `npm run android` to build and launch the app on a physical device.
2. Press and hold over the text and button to confirm that it is focusable on talkback.
3. Do a 2 finger swipe up (or down) gesture to trigger the `Gesture.Pan`. Note that the gesture is not actually connected to anything.
4. Press and hold over the text and button again.

You should observe that step 4 fails to work.

### Snack or a link to a repository

https://github.com/tpcstld/rn-stuff/tree/tpcstld/pan-gesture-bug

### Gesture Handler version

2.23.1

### React Native version

0.77.1

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

None

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Pixel 7

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

As stated in [this comment](https://github.com/software-mansion/react-native-gesture-handler/issues/3407#issuecomment-2658466924), `TalkBack` uses `Hover` events. The fact that they were not handled in `RNGestureHandlerRootHelper` resulted in buttons being unresponsive after other gesture had been activated. 

Fixes #3407 

## Test plan

Tested on the reproduction code from issue

### CODE REVIEW

File: android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt [hunk 1]
```diff
@@ -58,19 +58,29 @@ class RNGestureHandlerRootHelper(private val context: ReactContext, wrappedView:
...
       }
     }
 
+    override fun onHandle(event: MotionEvent, sourceEvent: MotionEvent) {
+      handleEvent(event)
+    }
+
+    override fun onHandleHover(event: MotionEvent, sourceEvent: MotionEvent) {
+      handleEvent(event)
+    }
```
Comment (j-piasecki) [inline android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt:82]:
```suggestion
    override fun onHandle(event: MotionEvent, sourceEvent: MotionEvent) = handleEvent(event)

    override fun onHandleHover(event: MotionEvent, sourceEvent: MotionEvent) = handleEvent(event)
```

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt [hunk 2]
```diff
@@ -470,6 +471,13 @@ class GestureHandlerOrchestrator(
     return found
   }
 
+  private fun shouldHandlerSkipHoverEvents(handler: GestureHandler<*>, action: Int): Boolean {
+    val shouldSkipEvents =
+      handler !is HoverGestureHandler && handler !is RNGestureHandlerRootHelper.RootViewGestureHandler
+
+    return action in listOf(MotionEvent.ACTION_HOVER_EXIT, MotionEvent.ACTION_HOVER_ENTER, MotionEvent.ACTION_HOVER_MOVE) && shouldSkipEvents
```
Comment (j-piasecki) [inline android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt:478]:
```suggestion
    return shouldSkipEvents && action in listOf(MotionEvent.ACTION_HOVER_EXIT, MotionEvent.ACTION_HOVER_ENTER, MotionEvent.ACTION_HOVER_MOVE)
```

Imo, it's easier to read this way

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt [hunk 3]
```diff
@@ -480,8 +488,11 @@ class GestureHandlerOrchestrator(
             continue
           }
 
-          // we don't want to extract gestures other than hover when processing hover events
-          if (event.action in listOf(MotionEvent.ACTION_HOVER_EXIT, MotionEvent.ACTION_HOVER_ENTER, MotionEvent.ACTION_HOVER_MOVE) && handler !is HoverGestureHandler) {
+          // We don't want to extract gestures other than hover when processing hover events.
+          // There's only one exception - RootViewGestureHandler. TalkBack uses hover events,
+          // so we need to pass them into RootViewGestureHandler, otherwise press and hold
+          // gesture stops working correctly (see https://github.com/software-mansion/react-native-gesture-handler/issues/3407)
```
Comment (j-piasecki) [inline android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt:494]: I have mixed feelings on this - on the one hand, it's nice having the explanation on the call site, but on the other, it would be nice to have in alongside the implementation.

File: android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt (hunk 1 above)
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt]: Done in [c1a9158](https://github.com/software-mansion/react-native-gesture-handler/pull/3462/commits/c1a91588266e9604bcc22ccd3f5b220383cf51a2)

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt (hunk 2 above)
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt]: I agree, done in [c1a9158](https://github.com/software-mansion/react-native-gesture-handler/pull/3462/commits/c1a91588266e9604bcc22ccd3f5b220383cf51a2)

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt (hunk 3 above)
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt]: I've moved this comment above the implementation ([c1a9158](https://github.com/software-mansion/react-native-gesture-handler/pull/3462/commits/c1a91588266e9604bcc22ccd3f5b220383cf51a2)). I think name of this function is enough self-explanatory, so we don't have to write a comment alongside call.

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt [hunk 4]
```diff
@@ -470,6 +471,17 @@ class GestureHandlerOrchestrator(
...
 
+  // We don't want to extract gestures other than hover when processing hover events.
+  // There's only one exception - RootViewGestureHandler. TalkBack uses hover events,
+  // so we need to pass them into RootViewGestureHandler, otherwise press and hold
+  // gesture stops working correctly (see https://github.com/software-mansion/react-native-gesture-handler/issues/3407)
+  private fun shouldHandlerSkipHoverEvents(handler: GestureHandler<*>, action: Int): Boolean {
+    val shouldSkipEvents =
+      handler !is HoverGestureHandler && handler !is RNGestureHandlerRootHelper.RootViewGestureHandler
+
+    return shouldSkipEvents && action in listOf(MotionEvent.ACTION_HOVER_EXIT, MotionEvent.ACTION_HOVER_ENTER, MotionEvent.ACTION_HOVER_MOVE)
```
Comment (j-piasecki) [inline android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt:482]:
```suggestion
    val shouldSkipHoverEvents =
      handler !is HoverGestureHandler && handler !is RNGestureHandlerRootHelper.RootViewGestureHandler

    return shouldSkipHoverEvents && action in listOf(MotionEvent.ACTION_HOVER_EXIT, MotionEvent.ACTION_HOVER_ENTER, MotionEvent.ACTION_HOVER_MOVE)
```

**Review by j-piasecki — APPROVED** [review]
