### PR TITLE
[Jest] Don't fire callbacks on disabled gestures

### LINKED ISSUE #3117: fireGestureHandler should not trigger disabled gestures
### Description

Hello, I've been trying to write some tests for my library, however I've noticed `fireGestureHandler` is capable of triggering events in gestures whose enabled method has been set to `false`, is this the expected behavior?

### Steps to reproduce

Run the following code as a Jest test, expected behavior is the second gesture is not triggered and therefore the mock is not called, however the mock it's called regardless of whether the gesture is enabled or not.

```jsx
import React from 'react';
import Animated from 'react-native-reanimated';
import {
  Gesture,
  GestureDetector,
  type TapGesture,
} from 'react-native-gesture-handler';
import {
  fireGestureHandler,
  getByGestureTestId,
} from 'react-native-gesture-handler/jest-utils';
import { render } from '@testing-library/react-native';

type ComponentProps = {
  enabled: boolean;
  callback: () => void;
};

const Component = ({ enabled, callback }: ComponentProps) => {
  const tap = Gesture.Tap()
    .withTestId('tap')
    .enabled(enabled)
    .runOnJS(true)
    .onEnd(callback);

  return (
    <GestureDetector gesture={tap}>
      <Animated.View
        style={{ width: 200, height: 200, backgroundColor: 'orange' }}
      />
    </GestureDetector>
  );
};

describe('Some Random Tests', () => {
  type TestData = {
    title: string;
    enabled: boolean;
    timesCalled: number;
  };

  it.each<TestData>([
    { title: 'should trigger callback once', enabled: true, timesCalled: 1 },
    { title: 'should not trigger callback', enabled: false, timesCalled: 0 },
  ])('$title', ({ enabled, timesCalled }) => {
    const callback = jest.fn();
    render(<Component enabled={enabled} callback={callback} />);

    fireGestureHandler<TapGesture>(getByGestureTestId('tap'));

    expect(callback).toHaveBeenCalledTimes(timesCalled);
  });
});
```

### Snack or a link to a repository

code provided above

### Gesture Handler version

2.19.0

### React Native version

0.74.1

### Platforms

Android, iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

As pointed in #3117, `fireGestureHandler` runs callback function even if gesture has been marked as disabled with `enable(false)`. This PR removes this behavior. 

Closes #3117 

## Test plan

<details>
<summary>Run the following test:</summary>

```tsx
import React from 'react';
import { View } from 'react-native';
import Animated from 'react-native-reanimated';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
  TapGestureHandler,
  type TapGesture,
} from '../';
import { fireGestureHandler, getByGestureTestId } from '../jestUtils';
import { render } from '@testing-library/react-native';
import Mocks from '../mocks';

type ComponentProps = {
  enabled: boolean;
  callback: () => void;
};

const Component = ({ enabled, callback }: ComponentProps) => {
  const tap = Gesture.Tap()
    .withTestId('tap')
    .enabled(enabled)
    .runOnJS(true)
    .onEnd(callback);

  return (
    <GestureDetector gesture={tap}>
      <Animated.View
        style={{ width: 200, height: 200, backgroundColor: 'orange' }}
      />
    </GestureDetector>
  );
};

describe('Some Random Tests', () => {
  type TestData = {
    title: string;
    enabled: boolean;
    timesCalled: number;
  };

  it.each<TestData>([
    { title: 'should trigger callback once', enabled: true, timesCalled: 1 },
    { title: 'should not trigger callback', enabled: false, timesCalled: 0 },
  ])('$title', ({ enabled, timesCalled }) => {
    const callback = jest.fn();
    render(<Component enabled={enabled} callback={callback} />);

    fireGestureHandler<TapGesture>(getByGestureTestId('tap'));

    expect(callback).toHaveBeenCalledTimes(timesCalled);
  });
});

describe('Button test', () => {
  const callback = jest.fn();
  const { getByTestId } = render(
    <Mocks.RectButton enabled={false} onPress={callback} testID="btn" />
  );

  fireGestureHandler(getByTestId('btn'));

  expect(callback).toHaveBeenCalledTimes(0);
});

describe('Old API test', () => {
  const callback = jest.fn();
  const { getByTestId } = render(
    <GestureHandlerRootView>
      <TapGestureHandler testID="tap" onActivated={callback} enabled={false}>
        <View />
      </TapGestureHandler>
    </GestureHandlerRootView>
  );

  fireGestureHandler(getByTestId('tap'));

  expect(callback).toHaveBeenCalledTimes(0);
});
```

</details>

### CODE REVIEW

File: src/jestUtils/jestUtils.ts [hunk 1]
```diff
@@ -417,6 +418,7 @@ function getHandlerData(
       },
       handlerType: gesture.handlerName as HandlerNames,
       handlerTag: gesture.handlerTag,
+      enabled: gesture.config.enabled,
```
Comment (j-piasecki) [inline src/jestUtils/jestUtils.ts:421]: What about `<*GestureHandler>`?

Comment (m-bert) [reply src/jestUtils/jestUtils.ts:421]: Good catch! Added in [c8702ca](https://github.com/software-mansion/react-native-gesture-handler/pull/3119/commits/c8702cafd6a75e885431809b855e5d7f79a2d180)

**Review by j-piasecki — APPROVED** [review]

File: src/jestUtils/jestUtils.ts [hunk 2]
```diff
@@ -467,9 +470,13 @@ export function fireGestureHandler<THandler extends AllGestures | AllHandlers>(
   componentOrGesture: ReactTestInstance | GestureType,
   eventList: Partial<GestureHandlerTestEvent<ExtractConfig<THandler>>>[] = []
 ): void {
-  const { emitEvent, handlerType, handlerTag } =
+  const { emitEvent, handlerType, handlerTag, enabled } =
     getHandlerData(componentOrGesture);
 
+  if (enabled === false) {
```
Comment (Romick2005) [inline src/jestUtils/jestUtils.ts:476]: Do you need this strict type check? Would `if (!enabled) {` work for you then?

Comment (j-piasecki) [reply src/jestUtils/jestUtils.ts:476]: By default none of the props are initialized and default values are assumed. The default for `enabled` is `true` but the prop itself may be `undefined`, in which case `if (!enabled) {` wouldn't work.

Comment (Romick2005) [reply src/jestUtils/jestUtils.ts:476]: It is tricky way to consider boolean with 3 values true/false/undefined. But I got you it will work. Thank you for explanation!
