### PR TITLE
[macOS] Fix build on `fabric`

### LINKED ISSUE #3144: react-native-gesture-handler fails to build on react-native-macos with new architecture
### Description

Hi, react-native-gesture-handler cannot be built on react-native-macos with new architecture enabled.

image

This is due to iOS environment being expected in [RNGestureHandlerButtonComponentView.h](https://github.com/software-mansion/react-native-gesture-handler/blob/main/apple/RNGestureHandlerButtonComponentView.h).

Furthermore, even when importing AppKit instead for macOS, there are more issues in [RNGestureHandlerButtonComponentView.mm](https://github.com/software-mansion/react-native-gesture-handler/blob/main/apple/RNGestureHandlerButtonComponentView.mm), where `UIView` is used instead of the platform-independent `RNGHUIView`.

However, I don't know how to fix `[_buttonView mountChildComponentView:childComponentView index:index];` simply not working (existing?) on macOS.
`No visible @interface for 'RNGestureHandlerButton' declares the selector 'mountChildComponentView:index:'`

https://github.com/software-mansion/react-native-gesture-handler/blob/a6741a920718f35d04cccf621737a146eeff370d/apple/RNGestureHandlerButtonComponentView.mm#L43-L46

This line does work either with error `No visible @interface for 'RNGestureHandlerButton' declares the selector 'updateLayoutMetrics:oldLayoutMetrics:'`:

https://github.com/software-mansion/react-native-gesture-handler/blob/a6741a920718f35d04cccf621737a146eeff370d/apple/RNGestureHandlerButtonComponentView.mm#L85

See repro here:
https://github.com/hsjoberg/gesturehandlernewarchbug

### Steps to reproduce

Please see my repro.
But to do manually; start a new react-native community CLI project, initialize react-native-macos and add react-native-gesture handler to observe the error.

```
npx @react-native-community/cli init gesturehandlernewarchbug

cd gesturehandlernewarchbug/

yarn add react-native-macos@^0.75.0

npx react-native-macos-init

yarn add react-native-gesture-handler

cd macos

RCT_NEW_ARCH_ENABLED=1 pod install

# then start macos app via xcode or metro

```

Note: you may have to add bundleUrl fix too: https://github.com/microsoft/react-native-macos/issues/2164#issuecomment-2294816367

### Snack or a link to a repository

https://github.com/hsjoberg/gesturehandlernewarchbug

### Gesture Handler version

2.20.0

### React Native version

0.75

### Platforms

MacOS

### JavaScript runtime

JSC

### Workflow

React Native (without Expo)

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

None

### Device model

macOS

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

Right now Gesture Handler fails to build on macOS on new architecture. This PR brings changes necessary to fix this problem.

Fixes #3144.

## Test plan

Build macOS example app on new architecture.

### CODE REVIEW

File: apple/RNGestureHandlerButtonComponentView.mm [hunk 1]
```diff
@@ -21,6 +21,11 @@ @implementation RNGestureHandlerButtonComponentView {
   RNGestureHandlerButton *_buttonView;
 }
 
++ (BOOL)shouldBeRecycled
+{
+  return NO;
+}
```
Comment (j-piasecki) [inline apple/RNGestureHandlerButtonComponentView.mm:27]: Can we do this only on macOS?

File: apple/RNGestureHandlerButton.h [hunk 2]
```diff
@@ -19,4 +26,13 @@
 @property (nonatomic, assign) UIEdgeInsets hitTestEdgeInsets;
 @property (nonatomic) BOOL userEnabled;
 
+#if TARGET_OS_OSX
+#ifdef __cplusplus
+- (void)mountChildComponentView:(RNGHUIView<RCTComponentViewProtocol> *)childComponentView index:(NSInteger)index;
+- (void)unmountChildComponentView:(RNGHUIView<RCTComponentViewProtocol> *)childComponentView index:(NSInteger)index;
+- (void)updateLayoutMetrics:(const facebook::react::LayoutMetrics &)layoutMetrics
+           oldLayoutMetrics:(const facebook::react::LayoutMetrics &)oldLayoutMetrics;
+#endif
```
Comment (j-piasecki) [inline apple/RNGestureHandlerButton.h:35]: I actually have no idea whether it's safe to do (have method declarations behind a compile flag but not the implementation.

Why do it this way instead of just changing files where it was included to be Objective-C++?

Comment (m-bert) [reply apple/RNGestureHandlerButton.h:35]: This file was already change into `Obj-C++`. The thing is, changing it to `Obj-C++` is not enough and without this flag you'll get compilation errors. We talked about it with @piaskowyk and this was the solution that he came up with. Let us know if you see better one 😅

File: apple/RNGestureHandlerButtonComponentView.mm (hunk 1 above)
Comment (m-bert) [reply apple/RNGestureHandlerButtonComponentView.mm:28]: Sure, done in [29a3356](https://github.com/software-mansion/react-native-gesture-handler/pull/3154/commits/29a3356496840ce6d8eacc5c384ad32df35795c2)

Comment (j-piasecki) [reply apple/RNGestureHandlerButtonComponentView.mm:28]: Can you also add a comment explaining why it's done 😅?

**Comment by hsjoberg** [comment]
Can confirm that it fixes #3144 💯

File: apple/RNGestureHandlerButton.h (hunk 2 above)
Comment (m-bert) [reply apple/RNGestureHandlerButton.h:35]: Well, that makes sense.

Done in [9ebcbff](https://github.com/software-mansion/react-native-gesture-handler/pull/3154/commits/9ebcbff181ec0260c78581579bbd4885d8983bd5)

File: apple/RNGestureHandlerButtonComponentView.mm (hunk 1 above)
Comment (j-piasecki) [reply apple/RNGestureHandlerButtonComponentView.mm:28]: Bump

File: apple/RNGestureHandlerButton.h (hunk 2 above)
Comment (j-piasecki) [reply apple/RNGestureHandlerButton.h:35]: Checks for `__cplusplus` shouldn't be necessary in that case

Comment (m-bert) [reply apple/RNGestureHandlerButton.h]: You're right, done in [d8d1772](https://github.com/software-mansion/react-native-gesture-handler/pull/3154/commits/d8d177295dced6a4e4e94696df2699f73d1faf19)

File: apple/RNGestureHandlerButtonComponentView.mm (hunk 1 above)
Comment (m-bert) [reply apple/RNGestureHandlerButtonComponentView.mm:30]: Sure 😅 

Done in [7bbb316](https://github.com/software-mansion/react-native-gesture-handler/pull/3154/commits/7bbb31637572b01285849e82a87431fdd36c0728)

**Review by j-piasecki — APPROVED** [review]
