### PR TITLE
Fix nested taps activation

### LINKED ISSUE #2739: Using same gesture in Gesture.Exclusive causes crash on Android
### Description

When using the same gesture in `Gesture.Exclusive` the app crashes on Android in version '~2.14.0'

I have a scenario shown on the screenshot. I want to have a tap target inside a tap target inside a double press target. Only one of the gestures should be activated at any one time.

I started by using `blocksExternalGesture` between the orange and blue tap gesture to achieve the effect. Which was when I noticed the crash, however it still crashes in the following code without it being in place.

On version `~2.12.0` it doesn't cause a crash, but both "orange and blue" taps are activated at the same time on Android. On iOS only one of "blue" and "orange" are activated at the same time. The behaviour for iOS is the same between `~2.12.0` and `~2.14.0`

I don't know what the expected behaviour is, if both "orange" and "blue" should activate, or only "orange" without using `blocksExternalGesture`. However it is inconsistent between platforms.

I have made the same repro with  `~2.12.0` and `~2.14.0`. Only `~2.12.0` is a Snack since Snacks doesn't support Expo SDK 50 yet (which has RNGH 2.14.0). 

It also occurs in bare workflow, which was how I noticed it (RN 0.72.4 and RNGH 2.14.1)

`~2.12.0`: https://snack.expo.dev/@jacobmolby/rngh-crash-repro
`~2.14.0`: https://github.com/jacobmolby/rngh-bug-repro

simulator_screenshot_A7195B2E-6A1A-4790-A04B-B1758FABFC11

Example that causes crash/inconsistent behaviour:

```javascript
import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated from 'react-native-reanimated';

const Showcase = () => {
  const [lastActions, setLastActions] = React.useState([]);

  const addAction = action => {
    setLastActions(actions => {
      const date = new Date();
      const time = date.toLocaleTimeString();

      if (actions.length >= 3) {
        actions.pop();
      }
      return [action + ': ' + time, ...actions];
    });
  };

  const longPressGesture = Gesture.LongPress()
    .onStart(() => {
      addAction('long press');
    })
    .runOnJS(true);

  const doubleTapGesture = Gesture.Tap()
    .numberOfTaps(2)
    .onStart(() => {
      addAction('double tap');
    })
    .runOnJS(true);

  const gesture = Gesture.Race(doubleTapGesture, longPressGesture);

  return (
    <View
      style={{
        flex: 1,
        backgroundColor: 'white',
        marginHorizontal: 20,
        marginVertical: 60,
      }}>
      <ScrollView contentContainerStyle={{ gap: 20 }}>
        <GestureDetector gesture={gesture}>
          <Animated.View style={styles.outer}>
            <Blue doubleTapGesture={doubleTapGesture} onAddAction={addAction} />
          </Animated.View>
        </GestureDetector>
        <View>
          {lastActions.map((action, index) => (
            <Text key={index}>
              {index} - {action}
            </Text>
          ))}
        </View>
        <View style={{ gap: 20 }}>
          <Text>
            <Bold>DoubleTap</Bold>: on all rectangles - should print "double
            tap" - no tap gesture should be recognized ✅
          </Text>
          <Text>
            <Bold>LongPress</Bold>: on all rectangles - should print "long
            press" - no tap gesture should be recognized ✅
          </Text>
          <Text>
            <Bold>Tap</Bold>: on red - should do nothing ✅
          </Text>
          <Text>
            <Bold>Tap</Bold>: on blue - should print "Blue: tap" ✅
          </Text>
          <Text>
            <Bold>Tap</Bold>: on orange - should print "Orange: tap" ⛔️ -
            Crashes on Android
          </Text>
        </View>
      </ScrollView>
    </View>
  );
};

export default Showcase;

const Blue = ({ doubleTapGesture, onAddAction }) => {
  const tapGesture = Gesture.Tap()
    .onStart(() => {
      onAddAction('Blue: tap');
    })
    .runOnJS(true);

  const composedGesture = Gesture.Exclusive(doubleTapGesture, tapGesture);

  return (
    <GestureDetector gesture={composedGesture}>
      <Animated.View style={styles.blue}>
        <Orange doubleTapGesture={doubleTapGesture} onAddAction={onAddAction} />
      </Animated.View>
    </GestureDetector>
  );
};

const Orange = ({ doubleTapGesture, onAddAction }) => {
  const tapGesture = Gesture.Tap()
    .onStart(() => {
      onAddAction('Orange: tap');
    })
    .runOnJS(true);

  return (
    <GestureDetector gesture={Gesture.Exclusive(doubleTapGesture, tapGesture)}>
      <Animated.View style={styles.orange}></Animated.View>
    </GestureDetector>
  );
};

const Bold = ({ children }) => {
  return <Text style={{ fontWeight: 'bold' }}>{children}</Text>;
};

const styles = StyleSheet.create({
  outer: {
    padding: 20,
    backgroundColor: 'red',
    width: 300,
    height: 200,
  },
  blue: {
    width: '80%',
    height: '80%',
    backgroundColor: 'blue',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  orange: {
    margin: 5,
    width: '50%',
    height: '50%',
    backgroundColor: 'orange',
  },
});

```

When the crash occurs on Android the the stack trace is the following:

```
FATAL EXCEPTION: main
Process: host.exp.exponent, PID: 8224
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
	at java.util.ArrayList$Itr.next(ArrayList.java:982)
	at aq.g.w(SourceFile:35)
	at aq.d.b0(SourceFile:46)
	at aq.d.B(SourceFile:12)
	at aq.y.O0(SourceFile:6)
	at aq.y.M0(SourceFile:1)
	at aq.x.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

### Steps to reproduce

Put a GestureDetector with Gesture.Exclusive inside another one and watch it crash on android

### Snack or a link to a repository

https://github.com/jacobmolby/rngh-bug-repro

### Gesture Handler version

2.12.0 and 2.14.0

### React Native version

0.72.4 and 0.73.2 

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Paper (Old Architecture)

### Build type

Debug mode

### Device

Real device

### Device model

Crash reproduced on both Galaxy A41 and Galaxy A52 5G

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

While working on #2739 we discovered that our orchestration process doesn't work as expected when we have nested `Tap` gestures . This PR introduces few changes that make those gestures work as intended. 

Fixes #2739 

## Test plan

Tested on example app and on modified code from issue.

<details>
<summary> Test code </summary>

```jsx
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated from 'react-native-reanimated';

const log = (e: any, handler: string) =>
  console.log(`[${e.handlerTag}][${handler}]: ${e.state}`);

const orangeTapGesture = Gesture.Tap()
  .runOnJS(true)
  .maxDeltaX(5)
  .onBegin((e) => log(e, 'Orange tap'))
  .onStart((e) => log(e, 'Orange tap'))
  .onFinalize((e, success) => {
    log(e, 'Orange tap');
    if (success) {
      console.log('---> Orange Tap <---');
    }
  });

const orangeDoubleTapGesture = Gesture.Tap()
  .numberOfTaps(2)
  .runOnJS(true)
  .onBegin((e) => log(e, 'Orange Double Tap'))
  .onStart((e) => log(e, 'Orange Double Tap'))
  .onFinalize((e, success) => {
    log(e, 'Orange Double Tap');
    if (success) {
      console.log('---> Orange Double Tap <---');
    }
  });

const blueTapGesture = Gesture.Tap()
  .runOnJS(true)
  .requireExternalGestureToFail(orangeTapGesture, orangeDoubleTapGesture)
  .onBegin((e) => log(e, 'Blue Tap'))
  .onStart((e) => log(e, 'Blue Tap'))
  .onFinalize((e, success) => {
    log(e, 'Blue Tap');
    if (success) {
      console.log('---> Blue Tap <---');
    }
  });

const blueDoubleTapGesture = Gesture.Tap()
  .numberOfTaps(2)
  .runOnJS(true)
  .onBegin((e) => log(e, 'Blue Double Tap'))
  .onStart((e) => log(e, 'Blue Double Tap'))
  .onFinalize((e, success) => {
    log(e, 'Blue Double Tap');
    if (success) {
      console.log('---> Blue Double Tap <---');
    }
  });

const redLongPressGesture = Gesture.LongPress()
  .runOnJS(true)
  .onBegin((e) => log(e, 'Red Longpress'))
  .onStart((e) => log(e, 'Red Longpress'))
  .onFinalize((e, success) => {
    log(e, 'Red Longpress');
    if (success) {
      console.log('---> Red Longpress <---');
    }
  });

const redDoubleTapGesture = Gesture.Tap()
  .numberOfTaps(2)
  .runOnJS(true)
  .onBegin((e) => log(e, 'Red Double Tap'))
  .onStart((e) => log(e, 'Red Double Tap'))
  .onFinalize((e, success) => {
    log(e, 'Red Double Tap');
    if (success) {
      console.log('---> Red Double Tap <---');
    }
  });

const Showcase = () => {
  const gesture = Gesture.Race(redDoubleTapGesture, redLongPressGesture);

  return (
    <View style={[styles.center, { flex: 1, backgroundColor: 'white' }]}>
      <GestureDetector gesture={gesture}>
        <Animated.View style={[styles.outer, styles.center]}>
          <Blue />
        </Animated.View>
      </GestureDetector>
    </View>
  );
};

export default Showcase;

const Blue = () => {
  const composedGesture = Gesture.Exclusive(
    blueDoubleTapGesture,
    blueTapGesture
  );

  return (
    <GestureDetector gesture={composedGesture}>
      <Animated.View style={[styles.blue, styles.center]}>
        <Orange />
      </Animated.View>
    </GestureDetector>
  );
};

const Orange = () => {
  const composedGesture = Gesture.Exclusive(
    orangeDoubleTapGesture,
    orangeTapGesture
  );

  return (
    <GestureDetector gesture={composedGesture}>
      <Animated.View style={styles.orange} />
    </GestureDetector>
  );
};

const styles = StyleSheet.create({
  center: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
  },

  outer: {
    backgroundColor: 'red',
    width: 400,
    height: 400,
    borderRadius: 200,
  },
  blue: {
    width: 250,
    height: 250,
    backgroundColor: 'blue',

    borderRadius: 175,
  },
  orange: {
    width: 100,
    height: 100,
    backgroundColor: 'orange',
    borderRadius: 50,
  },
});

```

</details>

### CODE REVIEW

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt [hunk 1]
```diff
@@ -108,7 +114,18 @@ open class GestureHandler<ConcreteGestureHandlerT : GestureHandler<ConcreteGestu
         return true
       }
     }
-    return false
+
+    if (this !is TapGestureHandler) {
+      return false
+    }
```
Comment (j-piasecki) [inline android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt:120]: This looks weird to me. Why not just make this method `open` and override it in `TapGestureHandler`?

File: src/web/tools/GestureHandlerOrchestrator.ts [hunk 2]
```diff
@@ -67,6 +67,17 @@ export default class GestureHandlerOrchestrator {
   }
 
   private tryActivate(handler: GestureHandler): void {
+    if (
+      this.gestureHandlers.some(
+        (otherHandler) =>
+          this.shouldHandlerWaitForOther(handler, otherHandler) &&
+          otherHandler.getState() === State.END
+      )
```
Comment (j-piasecki) [inline src/web/tools/GestureHandlerOrchestrator.ts:75]: Can you extract this to a helper method? Seeing something like `if (shouldBeCancelledByAlreadyFinishedHandler...)` is much more readable than this (name itself is questionable, but you get the point).

**Review by j-piasecki — CHANGES_REQUESTED** [review]

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt (hunk 1 above)
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt]: Done in [ed702f8](https://github.com/software-mansion/react-native-gesture-handler/pull/2759/commits/ed702f8b203bd641dee038628a5ac0ee1e01dab5)

File: src/web/tools/GestureHandlerOrchestrator.ts (hunk 2 above)
Comment (m-bert) [reply src/web/tools/GestureHandlerOrchestrator.ts]: Done in [2375a47](https://github.com/software-mansion/react-native-gesture-handler/pull/2759/commits/2375a475d759eee7b7e5a99a0983fbd83df02fe3)

File: android/src/main/java/com/swmansion/gesturehandler/core/TapGestureHandler.kt [hunk 3]
```diff
@@ -152,6 +152,24 @@ class TapGestureHandler : GestureHandler<TapGestureHandler>() {
...
+  override fun hasCommonPointers(other: GestureHandler<*>): Boolean {
+    if (super.hasCommonPointers(other)) {
+      return true
+    }
+
+    val cachedPointersIDs = getCachedPointersIDs()
+    val otherCachedPointerIDs = other.getCachedPointersIDs()
+    val nextCachedPointerID = getNextCachedPointerID()
+
+    for (i in 0 until nextCachedPointerID) {
```
Comment (j-piasecki) [inline android/src/main/java/com/swmansion/gesturehandler/core/TapGestureHandler.kt:164]: Is this necessary? If I understand correctly, pointers will be clustered at the beginning anyway, so we can iterate over entire array and break when encountering `-1` no?

If so, then getter for getNextCachedPointerID can be removed.

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt [hunk 4]
```diff
@@ -788,6 +803,10 @@ open class GestureHandler<ConcreteGestureHandlerT : GestureHandler<ConcreteGestu
   val lastPositionInWindowY: Float
     get() = lastAbsolutePositionY + lastEventOffsetY - windowOffset[1]
 
+  fun getTrackedPointersIDs() = trackedPointerIDs
+  fun getCachedPointersIDs() = cachedPointersIDs
+  fun getNextCachedPointerID() = nextCachedPointerID
```
Comment (j-piasecki) [inline android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt:808]: Why not just make them public? They're `vals` anyway so they cannot be set and the getter doesn't protect you from modifying the collection.

(getNextCachedPointerID may not be necessary at all)

Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt]: Done in [d0081f3](https://github.com/software-mansion/react-native-gesture-handler/pull/2759/commits/d0081f372715604f391c7919fea49e811cc8f3a5)

File: src/web/tools/GestureHandlerOrchestrator.ts [hunk 5]
```diff
@@ -66,7 +66,20 @@ export default class GestureHandlerOrchestrator {
...
+  private shouldBeCancelledByFinishedHandler(handler: GestureHandler): boolean {
+    return this.gestureHandlers.some(
+      (otherHandler) =>
+        this.shouldHandlerWaitForOther(handler, otherHandler) &&
+        otherHandler.getState() === State.END
+    );
+  }
+
   private tryActivate(handler: GestureHandler): void {
+    if (this.shouldBeCancelledByFinishedHandler(handler)) {
```
[the remark this answers is not in the document]
Comment (m-bert) [reply src/web/tools/GestureHandlerOrchestrator.ts:78]: As far as I remember this change was necessary, but I'll check that.

[the remark this answers is not in the document]
Comment (m-bert) [reply src/web/tools/GestureHandlerOrchestrator.ts:78]: Okay, I've looked into it - we have to keep this change. However, we don't have to use pointers cache on android since this change seems to work even without those caches (I know that's `.ts` file, but it is the same change as the one in android).

File: android/src/main/java/com/swmansion/gesturehandler/core/TapGestureHandler.kt [hunk 6]
```diff
@@ -152,6 +152,24 @@ class TapGestureHandler : GestureHandler<TapGestureHandler>() {
     end()
   }
 
+  override fun hasCommonPointers(other: GestureHandler<*>): Boolean {
+    if (super.hasCommonPointers(other)) {
+      return true
+    }
+
+    for (i in cachedPointersIDs.indices) {
+      if (cachedPointersIDs[i] != other.cachedPointersIDs[i]) {
```
[the remark this answers is not in the document]
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/core/TapGestureHandler.kt]: It seems that we don't need that anyway, `shouldBeCancelledByFinishedHandler` is sufficient to fix our problem.

File: android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt [hunk 7]
```diff
@@ -22,6 +23,14 @@ class GestureHandlerOrchestrator(
   private val gestureHandlers = arrayListOf<GestureHandler<*>>()
   private val awaitingHandlers = arrayListOf<GestureHandler<*>>()
   private val preparedHandlers = arrayListOf<GestureHandler<*>>()
+
+  // In `onHandlerStateChange` method we iterate through `awaitingHandlers`, but calling `tryActivate` may modify this list.
+  // To avoid `ConcurrentModificationException` we iterate through copy. There is one more problem though - if handler was
+  // removed from `awaitingHandlers`, it was still present in copy of original list. This hashset helps us identify which handlers
+  // are really inside `awaitingHandlers`.
+  // `contains` method on HashSet has O(1) complexity, so calling it inside for loop won't result in O(n^2) (in opposite to ArrayList)
```
[the remark this answers is not in the document]
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt]: Done in [79f72c1](https://github.com/software-mansion/react-native-gesture-handler/pull/2759/commits/79f72c1a7c201b2b19460ca13f383debb1cc0a95).

File: android/src/main/java/com/swmansion/gesturehandler/core/TapGestureHandler.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/core/TapGestureHandler.kt]: Removed in [cfa0cd8](https://github.com/software-mansion/react-native-gesture-handler/pull/2759/commits/cfa0cd88035f4caef958d12a70ea3cdbad4bfe3d).

**Review by j-piasecki — APPROVED** [review]
