### PR TITLE
[iOS] Fix `activeOpacity` in `BorderlessButton`

### LINKED ISSUE #3426: activeOpacity on BorderlessButton does not work on iOS
### Description

`<BorderlessButton activeOpacity={.7} borderless={false}/>` was supposed to make it opaque on iOS, however it does nothing.

### Steps to reproduce

1. <BorderlessButton activeOpacity={.3} borderless={false}/>
2. Click on it.

### Snack or a link to a repository

https://snack.expo.dev/@rosterelf/borderless-button?platform=ios

### Gesture Handler version

2.24.0

### React Native version

0.77.1

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo managed workflow

### Architecture

Fabric (New Architecture)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone SE 18.2

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

Currently `activeOpacity` property in `BorderlessButton` doesn't work. It seems like it was broken by #2903. In this PR, `AnimatedBaseButton` is created from `InnerBaseButton` instead of `BaseButton` (which is a wrapper), so that props are correctly passed into animated view.

Fixes #3426 

## Test plan

<details>
<summary>Tested on the following example:</summary>

```jsx
import React, { useEffect, useRef } from 'react';
import { StyleSheet } from 'react-native';
import {
  BorderlessButton,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';

export default function EmptyExample() {
  const buttonRef = useRef(null);

  useEffect(() => {
    console.log(buttonRef);
  }, [buttonRef]);

  return (
    <GestureHandlerRootView style={styles.container}>
      <BorderlessButton
        activeOpacity={0.7}
        ref={buttonRef}
        style={{ width: 100, height: 25, backgroundColor: 'crimson' }}
      />
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
```

</details>

### CODE REVIEW

File: src/components/GestureButtons.tsx [hunk 1]
```diff
@@ -146,12 +146,17 @@ class InnerBaseButton extends React.Component<BaseButtonWithRefProps> {
...
+const AnimatedInnerBaseButton =
+  Animated.createAnimatedComponent<typeof InnerBaseButton>(InnerBaseButton);
+
 export const BaseButton = React.forwardRef<
   any,
   Omit<BaseButtonProps, 'innerRef'>
 >((props, ref) => <InnerBaseButton innerRef={ref} {...props} />);
 
-const AnimatedBaseButton = Animated.createAnimatedComponent(BaseButton);
+const AnimatedBaseButton = React.forwardRef<any, BaseButtonWithRefProps>(
```
Comment (latekvo) [inline src/components/GestureButtons.tsx:157]: I think we can narrow down this, and other `any` instances to `React.ComponentType`

Comment (m-bert) [reply src/components/GestureButtons.tsx]: Done in [f8d7629](https://github.com/software-mansion/react-native-gesture-handler/pull/3433/commits/f8d7629b8e58e7ec0f4a244f86be3bf97767c392)

Comment (latekvo) [reply src/components/GestureButtons.tsx]: I think you might've missed the `any` occurrence on line `153`. 
Were there some type issues when changing that occurrence from `any` to `React.ComponentType`?

Comment (m-bert) [reply src/components/GestureButtons.tsx]: You're right, fixed in [b22b0fc](https://github.com/software-mansion/react-native-gesture-handler/pull/3433/commits/b22b0fc56980ba08271057a223d7942485b67233)
