### PR TITLE
[web] Add support for two finger pan

### LINKED ISSUE #800: Support panning with touchpads
When providing apps that work across touch devices and laptops with touchpads - which I guess is the common case when using Hammer - the natural way to interact is two-finger swiping to pan and swipe. I'm getting bug reports on this because people feel "swipe isn't working" as they expect, it's simply the UX one would expect (I know it applies to Macs, but I guess it applies to other platforms as well).

I personally feel this might fit best in Hammer - but there seems to be a hesitation to add this to the core library. I had a look at implementing this myself but I'm just not familiar enough with Hammer. Maybe someone that's more familiar with it could have a look? Would be much appreciated :)

### PR DESCRIPTION
**Pull request by m-bert**
## Description

This PR adds support for two finger panning on touchpad on `web`.

>[!WARNING]
> Two finger gestures may be used as system/browser gestures (for example `swipe` to go back). This PR doesn't handle these cases.

## Implementation

Implementation is based on [WheelEvents](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event). This leads to some limitations - whole state flow of `Pan` has to be managed inside one callback (`onWheel`).

### Ending gesture

Starting gesture is easy, in contrast to ending it. To finish gesture we use `timeout`  - if no `wheel event` was received since `setTimeout` was called, we can end gesture. 

### `Mouse` vs `Touchpad`

It is hard to determine whether `mouse` or `touchpad` was used to start the gesture. `WheelEvent` doesn't have any information about the device, therefore we have to use heuristics to check that. 

>[!NOTE]
> You cannot start gesture with mouse scroll.

To see if events were generated with mouse, we check whether `wheelDeltaY` property (which is now [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event#event_properties)) of event is multiple of `120`. In short, this is standard `wheel delta` for mouse. Here you can find useful links that will tell more about why it works:

- https://stackoverflow.com/questions/10744645/detect-touchpad-vs-mouse-in-javascript
- https://devblogs.microsoft.com/oldnewthing/20130123-00/?p=5473  

>[!CAUTION]
> While this will work most of the times, it is possible that user will somehow generate this specific `wheel delta` with touchpad and gesture will not be recognized correctly.

Closes #800

## Test plan

Tested on new _**Two finger Pan**_ example

### CODE REVIEW

File: example/App.tsx [hunk 1]
```diff
@@ -209,6 +210,11 @@ const EXAMPLES: ExamplesSection[] = [
         unsupportedPlatforms: new Set(['android', 'ios', 'macos']),
       },
       { name: 'Stylus data', component: StylusData },
+      {
+        name: 'Two finger Pan',
+        component: TwoFingerPan,
+        unsupportedPlatforms: new Set(['android', 'macos', 'ios']),
```
Comment (j-piasecki) [inline example/App.tsx:216]:
```suggestion
        unsupportedPlatforms: new Set(['android', 'macos']),
```

Shouldn't this prop also work on iPads?

File: example/src/release_tests/twoFingerPan/index.tsx [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+  const clampColor = (sv: SharedValue<number>) =>
+    sv.value < 0 ? 0 : sv.value > 255 ? 255 : sv.value;
+
+  const pan = Gesture.Pan()
+    .onChange((event) => {
+      r.value -= event.changeY;
+      b.value += event.changeX;
+
+      r.value = clampColor(r);
+      b.value = clampColor(b);
```
Comment (j-piasecki) [inline example/src/release_tests/twoFingerPan/index.tsx:26]:
```suggestion
const clampColor = (v: number) => Math.min(255, Math.max(0, v));

export default function TwoFingerPan() {
  const r = useSharedValue(128);
  const b = useSharedValue(128);

  const pan = Gesture.Pan()
    .onChange((event) => {
      r.value = clampColor(r.value - event.changeY);
      b.value = clampColor(b.value + event.changeX);
```

File: example/src/release_tests/twoFingerPan/index.tsx [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+
+      console.table({ red: r.value, blue: b.value });
```
Comment (j-piasecki) [inline example/src/release_tests/twoFingerPan/index.tsx:28]: Is this log needed?

File: src/web/handlers/PanGestureHandler.ts [hunk 4]
```diff
@@ -351,6 +361,70 @@ export default class PanGestureHandler extends GestureHandler {
     }
   }
 
+  private scheduleWheelEnd(event: AdaptedEvent) {
+    this.endWheelTimeout = setTimeout(() => {
+      if (this.receivedWheelEvent) {
+        return;
+      }
```
Comment (j-piasecki) [inline src/web/handlers/PanGestureHandler.ts:368]: Why is this needed when the timeout is cleared in `onWheel`? And why not clean it here, before scheduling a new one?

File: src/web/handlers/PanGestureHandler.ts [hunk 5]
```diff
@@ -351,6 +361,70 @@ export default class PanGestureHandler extends GestureHandler {
...
+
+      this.end();
+      this.tracker.removeFromTracker(event.pointerId);
+      this.currentState = State.UNDETERMINED;
+
+      this.wheelDevice = WheelDevice.UNDETERMINED;
+    }, 30);
```
Comment (j-piasecki) [inline src/web/handlers/PanGestureHandler.ts:375]: Shouldn't this be configurable?

File: src/web/handlers/PanGestureHandler.ts [hunk 6]
```diff
@@ -351,6 +361,70 @@ export default class PanGestureHandler extends GestureHandler {
...
+    clearTimeout(this.endWheelTimeout);
+
+    if (this.currentState === State.UNDETERMINED) {
+      this.wheelDevice =
+        event.wheelDeltaY! % 120 !== 0
+          ? WheelDevice.TOUCHPAD
+          : WheelDevice.MOUSE;
+
+      if (this.wheelDevice === WheelDevice.MOUSE) {
+        this.scheduleWheelEnd(event);
```
Comment (j-piasecki) [inline src/web/handlers/PanGestureHandler.ts:398]: 1. Do we need to schedule in this case instead of ending outright?
2. Do we need to end here at all? `begin` is called after this condition, so we shouldn't even get there with mouse, no?

File: src/web/tools/PointerEventManager.ts [hunk 7]
```diff
@@ -200,7 +217,16 @@ export default class PointerEventManager extends EventManager<HTMLElement> {
...
   }
 
-  protected mapEvent(event: PointerEvent, eventType: EventTypes): AdaptedEvent {
+  protected mapEvent(
+    event: PointerEvent | WheelEvent,
+    eventType: EventTypes
+  ): AdaptedEvent {
+    return event instanceof PointerEvent
+      ? this.mapPointerEvent(event, eventType)
+      : this.mapWheelEvent(event);
```
Comment (j-piasecki) [inline src/web/tools/PointerEventManager.ts:226]: We may want to redesign the event manager system in the future. We now have `PointerEventManager` that needs to check whether the event it receives is a `PointerEvent` which seems wrong to me.

**Review by j-piasecki — COMMENTED** [review]
Have you checked if the behavior is the same as on iPad?

**Comment by latekvo** [comment]
As far as I see, `WheelEvent.wheelDeltaY` [isn't supported on firefox](https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event), would it be possible to resort to other heuristics like having a threshold on `WheelEvent.deltaY` in combination with `WheelEvent.deltaMode` for that browser?

File: src/web/tools/PointerEventManager.ts (hunk 7 above)
Comment (m-bert) [reply src/web/tools/PointerEventManager.ts:226]: There's nothing wrong with adding another event manager, but I'm not exactly sure how would it work. Adding `MouseEventManager` doesn't make much sense at this point for me. Also, this manager would have only one method - `onWheel`.

On the other hand, `KeyboradManager` also has one callback, so maybe it is fine 😅

File: src/web/handlers/PanGestureHandler.ts (hunk 5 above)
Comment (m-bert) [reply src/web/handlers/PanGestureHandler.ts:375]: I'm not sure, should it? I was to move it to a constant but it seems that I've missed it. Either way, do we want to give users permission to change this value? I think we can stick to one that works ok, but leaving it open for customization also makes sense.

File: src/web/handlers/PanGestureHandler.ts (hunk 6 above)
Comment (m-bert) [reply src/web/handlers/PanGestureHandler.ts:398]: If we don't schedule cleanup, wheelDevice won't be set to `UNDETERMINED`. I'm not sure if we want to set it here though. However, we can call `end` only if handler was `active`.

File: example/App.tsx (hunk 1 above)
Comment (m-bert) [reply example/App.tsx]: It should 😅

Comment (m-bert) [reply example/App.tsx]: Brought back in [dc59483](https://github.com/software-mansion/react-native-gesture-handler/pull/3163/commits/dc59483274fb14a3478a0e95a3958080a44c5bbd)

File: src/web/handlers/PanGestureHandler.ts (hunk 4 above)
Comment (m-bert) [reply src/web/handlers/PanGestureHandler.ts]: At first I wondered if the situation below is possible:

```tsx
this.receivedWheelEvent = true;
// execute `scheduleWheelEnd` here
clearTimeout(this.endWheelTimeout);
```

but we believe that it is not possible because of how event loop works.

So yes, it is not necessary and I've removed it in [a640c0c](https://github.com/software-mansion/react-native-gesture-handler/pull/3163/commits/a640c0c7700d96d66b95ecda06b1bf8c7bd730c3)

File: src/web/handlers/PanGestureHandler.ts (hunk 6 above)
Comment (m-bert) [reply src/web/handlers/PanGestureHandler.ts:392]: Also changed in [a640c0c](https://github.com/software-mansion/react-native-gesture-handler/pull/3163/commits/a640c0c7700d96d66b95ecda06b1bf8c7bd730c3)

**Comment by m-bert** [comment]
>Overall, would it be possible to detect that mouse is not being used instead of checking if it is?

As discussed, I think there's no better way to check that (but I'm open to discussion if you do find a better approach).

>would it be possible to resort to other heuristics like having a threshold on WheelEvent.deltaY in combination with WheelEvent.deltaMode for that browser?

Values of `deltaY` differ between browsers when it comes to mouse. Also `deltaMode` is the same for touchpad and for mouse.

>The current method seems to be very prone to false positives when it comes to detecting touchpad being used.

Activating on mouse wheel is a side effect of this feature that is not affecting main functionality.

**Comment by m-bert** [comment]
> Have you checked if the behavior is the same as on iPad?

I did and indeed it does (at least the example does) 😅

File: src/web/tools/PointerEventManager.ts (hunk 7 above)
Comment (m-bert) [reply src/web/tools/PointerEventManager.ts]: Okay, I've discussed it with @latekvo and we decided that it will be ok to add `WheelEventManager`. Done in [bf008b1](https://github.com/software-mansion/react-native-gesture-handler/pull/3163/commits/bf008b19202cc5d23b4bfa6c68fd4eec32d8c5ce)

File: example/src/release_tests/twoFingerPan/index.tsx [hunk 8]
```diff
@@ -0,0 +1,55 @@
...
+export default function TwoFingerPan() {
+  const r = useSharedValue(128);
+  const b = useSharedValue(128);
+
+  const pan = Gesture.Pan()
+    .onChange((event) => {
+      r.value = clampColor(r.value - event.changeY);
+      b.value = clampColor(b.value + event.changeX);
+    })
+    .runOnJS(true)
```
Comment (j-piasecki) [inline example/src/release_tests/twoFingerPan/index.tsx:23]: Why does it need to run on the JS thread?

**Review by j-piasecki — APPROVED** [review]

File: src/web/handlers/PanGestureHandler.ts (hunk 5 above)
Comment (j-piasecki) [reply src/web/handlers/PanGestureHandler.ts:374]: I guess we can leave it for now and see if there's a demand for it.

File: example/src/release_tests/twoFingerPan/index.tsx (hunk 8 above)
Comment (m-bert) [reply example/src/release_tests/twoFingerPan/index.tsx:23]: Because this example is also available on iOS 😅

Comment (j-piasecki) [reply example/src/release_tests/twoFingerPan/index.tsx:23]: What does it change?

Isn't making `clampColor` a worklet enough?

Comment (m-bert) [reply example/src/release_tests/twoFingerPan/index.tsx:23]: You're right, it is. I don't think it needs a PR though 😅
