### PR TITLE
[iOS] Fix `GestureDetector` on `Text`

### LINKED ISSUE #3581: iOS Fabric: Gesture.tap() worked on 0.78.2, no longer at 0.80
### Description

```
import {
    Gesture,
    GestureDetector,
} from 'react-native-gesture-handler';
```

/../

```
const doubleTap = Gesture.Tap()
        .maxDuration(1250)
        .numberOfTaps(2)
        .onStart(() => {
            if (prodInfo && typeof prodInfo !== "string") {
            handleConfirmStart(prodInfo.start, false);
            handleConfirmStop(prodInfo.stop, false);
            }
        });
```

/../

```
return (
<View>
 <GestureDetector gesture={Gesture.Exclusive(doubleTap)}>
                    <Text style={styles.txt50}>
                        {" - "}</Text>
                </GestureDetector>
</View>)
```

This used to work on 0.78.2. It no longer does. It still works on Android and Fabric though. I have tried with a simple console.log in onStart() which does not fire either.

Please let me know it anyone else is experiencing the same. If not, it might be that I'm specifically looking for double taps on links in another nav screen. Not sure why this would stop working on 0.80 though.

It is the same in both debug on iPhone 16 Pro simulator and release on real iPhone 14 device. Both on iOS 18 (which worked on 78.2).

### Steps to reproduce

Please see above.

### A link to a [Gist](https://gist.github.com/), an [Expo Snack](https://snack.expo.io/) or a link to a repository based on [this template](https://github.com/react-native-community/reproducer-react-native) that reproduces the bug.

www.unfortunatelynot.com

### Gesture Handler version

2.26.0

### React Native version

0.80.0

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

React Native (without Expo)

### Architecture

New Architecture (Fabric)

### Build type

Debug mode

### Device

iOS simulator

### Device model

iPhone 16 Pro

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
### Problem

Currently the following configuration:

```jsx
<GestureDetector ... >
  <Text> ... </Text>
</GestureDetector>
```

does not work on `iOS`. This is due to change `react-native` introduced in 0.79 - `hitTest` in `RCTParagraphTextView` now returns `nil` by default ([see here](https://github.com/facebook/react-native/blob/dcbbf275cbc4150820691a4fbc254b198cc92bdd/packages/react-native/React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentView.mm#L379)). This results in native `UIGestureRecognizer` not responding to touches.

### Solution

We no longer attach native recognizer to `RCTParagraphTextView`, but to its parent - `RCTParagraphComponentView`. The problem with this approach is that `handleGesture` method uses `reactTag` property, which on `RCTParagraphComponentView` is `nil`. This is why we use `reactTag` from `RCTParagraphTextView` when sending event to `JS` side.

Fixes #3581

## Test plan

<details>
<summary>Tested on the following code:</summary>

```jsx
import React from 'react';
import { StyleSheet, Text } from 'react-native';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';

export default function EmptyExample() {
  const g = Gesture.Tap().onEnd(() => {
    console.log('Tapped!');
  });

  return (
    <GestureHandlerRootView style={styles.container}>
      <GestureDetector gesture={g}>
        <Text>
          Click me
          <Text> Me too! </Text>
        </Text>
      </GestureDetector>
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
```

</details>

### CODE REVIEW

File: packages/react-native-gesture-handler/apple/RNGestureHandler.mm [hunk 1]
```diff
@@ -215,15 +216,31 @@ - (UITouchType)getPointerType
...
+- (BOOL)isViewParagraphComponent:(RNGHUIView *)view
+{
+  return [view isKindOfClass:[RCTParagraphComponentView class]];
+}
+#endif
+
 - (void)bindToView:(RNGHUIView *)view
 {
 #if !TARGET_OS_OSX
   view.userInteractionEnabled = YES;
```
Comment (j-piasecki) [inline packages/react-native-gesture-handler/apple/RNGestureHandler.mm]: I'd assume this should be set on the same view as the rest of properties

File: packages/react-native-gesture-handler/apple/RNGestureHandler.mm [hunk 2]
```diff
@@ -249,12 +266,27 @@ - (RNGestureHandlerEventExtraData *)eventExtraData:(UIGestureRecognizer *)recogn
...
+
 - (void)handleGesture:(UIGestureRecognizer *)recognizer
 {
+  RNGHUIView *view = [self chooseViewForInteraction:recognizer];
+
   // it may happen that the gesture recognizer is reset after it's been unbound from the view,
   // it that recognizer tried to send event, the app would crash because the target of the event
   // would be nil.
-  if (recognizer.view.reactTag == nil) {
+  if (view == nil) {
```
Comment (j-piasecki) [inline packages/react-native-gesture-handler/apple/RNGestureHandler.mm]:
```suggestion
  if (view.reactTag == nil) {
```

Are you sure that all other views will have the react tag set?

Comment (m-bert) [reply packages/react-native-gesture-handler/apple/RNGestureHandler.mm]: Changed in [36e3441](https://github.com/software-mansion/react-native-gesture-handler/pull/3591/commits/36e3441b92174277f806f3f2fbea28b7f13bf730)

File: packages/react-native-gesture-handler/apple/RNGestureHandler.mm (hunk 1 above)
Comment (m-bert) [reply packages/react-native-gesture-handler/apple/RNGestureHandler.mm]: While it seemed to work fine, I agree that it is a good idea to move it to `recognizerView`. Done in [3d11ef6](https://github.com/software-mansion/react-native-gesture-handler/pull/3591/commits/3d11ef61470eb892113a95b95e84a8b78ea9ab45)

**Review by j-piasecki — APPROVED** [review]
I assume you've tested this change on older versions of RN (0.78) as well.

**Comment by m-bert** [comment]
> I assume you've tested this change on older versions of RN (0.78) as well.

If by **_tested_** you mean tested attached example then yes, I did 😅

**Comment by Daumis102** [comment]
Hi, I'm running into this as well. Any idea when this will be released?

**Comment by m-bert** [comment]
Hi @Daumis102! 

> Any idea when this will be released?

I cannot give any ETA since we don't have release plans now. But I will keep that in mind and discuss it with the team 😅

**Comment by m-bert** [comment]
Hi @Daumis102! FYI, I've just released 2.27.2 which includes this PR 😅

**Comment by Daumis102** [comment]
Thank you!
