### PR TITLE
[Android] Fix `onTouches*` callbacks being called for all gestures

### LINKED ISSUE #3543: [Android] Touches up/down callbacks fired on multiple gesture detectors when should fire for only one
### Description

I noticed that the `onTouchesDown` and `onTouchesUp` callback is being fired ona all currently touched gesture detectors when I start/stop touching just one of them but keep touching the other one.

The example, on which I tested it it works, is very simple and consists of just 2 boxes with gesture detectors:

Image

<details>
<summary>Example source code</summary>

```tsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';

type BoxProps = {
  label: string;
};

function Box({ label }: BoxProps) {
  const manual = Gesture.Manual()
    .onTouchesDown(() => {
      console.log('down', label);
    })
    .onTouchesUp(() => {
      console.log('up', label);
    })
    .onTouchesCancelled(() => {
      console.log('cancelled', label);
    });

  return (
    <GestureDetector gesture={manual}>
      <View style={styles.box}>
        <Text style={styles.text}>{label}</Text>
      </View>
    </GestureDetector>
  );
}

export default function EmptyExample() {
  return (
    <View style={styles.container}>
      <Box label="1" />
      <Box label="2" />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  box: {
    width: 100,
    height: 100,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
});
```
</details>

### Android

https://github.com/user-attachments/assets/823254fe-9a5a-44db-94c5-b8d86096a315

### iOS

https://github.com/user-attachments/assets/9abbdf35-d0f8-4048-bed8-c43f77cbcfc3

### Steps to reproduce

1. I pressed the first box (with number 1) and didn't release the finger
2. I was tapping on the second box (with number 2) - started and stopped pressing for a few times
3. I finally released the finger from the first box (number 1)

### A link to a [Gist](https://gist.github.com/), an [Expo Snack](https://snack.expo.io/) or a link to a repository based on [this template](https://github.com/react-native-community/reproducer-react-native) that reproduces the bug.

https://snack.expo.dev/JaZCc4_vZlmyDOFHRlMEs

### Gesture Handler version

2.25.0 (and older)

### React Native version

0.80.0-rc.4 (and older)

### Platforms

Android

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

Logic behind sending touch events on `android` dispatches events into all gesture handlers registered in the orchestrator. This means that interaction with one `GestureDetector` triggers callbacks on the others. This PR adds check for tracked pointer, so that handlers respond only to those that they are tracking.

Fixes #3543

## Test plan

<details>

<summary>Tested on the following example:</summary>

```jsx
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import {
  Gesture,
  GestureDetector,
  GestureHandlerRootView,
} from 'react-native-gesture-handler';

type BoxProps = {
  label: string;
};

function Box({ label }: BoxProps) {
  const manual = Gesture.Manual()
    .onTouchesDown((e) => {
      console.log('down', label, e.handlerTag);
    })
    .onTouchesUp((e) => {
      console.log('up', label, e.handlerTag);
    })
    .onTouchesCancelled(() => {
      console.log('cancelled', label);
    });

  return (
    <GestureDetector gesture={manual}>
      <View style={styles.box}>
        <Text style={styles.text}>{label}</Text>
      </View>
    </GestureDetector>
  );
}

export default function EmptyExample() {
  return (
    <GestureHandlerRootView style={styles.container}>
      <Box label="1" />
      <Box label="2" />
    </GestureHandlerRootView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  box: {
    width: 100,
    height: 100,
    backgroundColor: 'red',
    alignItems: 'center',
    justifyContent: 'center',
  },
  text: {
    color: 'white',
    fontSize: 20,
    fontWeight: 'bold',
  },
});
```

</details>

### CODE REVIEW

File: packages/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt [hunk 1]
```diff
@@ -249,8 +249,11 @@ class GestureHandlerOrchestrator(
     // on Arrays.sort providing a stable sort (as children are registered in order in which they
     // should be tested)
     preparedHandlers.sortWith(handlersComparator)
+
     for (handler in preparedHandlers) {
-      deliverEventToGestureHandler(handler, event)
+      if (handler.isTrackingPointer(event.getPointerId(event.actionIndex))) {
```
Comment (j-piasecki) [inline packages/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt]: Can this be a method on `GestureHandler`? Something like `handler.wantsToHandleEvent(event)`.

Comment (m-bert) [reply packages/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandlerOrchestrator.kt]: Added `shouldHandleTouchEvent` in [373041a](https://github.com/software-mansion/react-native-gesture-handler/pull/3596/commits/373041a86b1d9d188c8ff10bd5424e0faf47dcbc).
