### PR TITLE
[Android] Fix `Hover` blocking scrolling with mouse wheel

### LINKED ISSUE #3064: `Hover` nested in `ScrollView` and scrolling `ScrollView` not working simultanously on Android
### Description

I'm trying to use `Gesture.Hover` in order to visualize hover effects with external mouse usage on react-native mobile (non-web).

I have a (global) `ScrollView` that wraps screens, that might include interactive elements (such as `Pressable`s). These `Pressable`s need to be visible via mouse hover. The problem is, that the `GestureDetector` appears to interfer with scrolling events. I have tried setting `simultaneousWithExternalGesture` with a ref to the scrollview, but that doesn't seem to change anything.

This does **not** apply to iOS. Everything works fine there.

Other (related) issues tend to focus on conflicting `Gesture.Pan`, but I'm having trouble with `Hover` as well.
related issues: https://github.com/software-mansion/react-native-gesture-handler/issues/2496, https://github.com/software-mansion/react-native-gesture-handler/issues/2616

also, here's a video demonstrating the below snack example:

https://github.com/user-attachments/assets/36d8104a-29c2-482e-9f34-29bbeb32679c

### Steps to reproduce

1. add scrollview (with as many items as needed to scroll but without any `GestureDetector`)
2. add items with `GestureDetector`, setting `Gesture.Hover`
3. try to scroll via mouse wheel inside the items without and with `GestureDetector`

alternatively, open up the below Expo Snack and scan with Expo Go

### Snack or a link to a repository

https://snack.expo.dev/@d.timur/biased-indigo-cheese

### Gesture Handler version

2.16.1

### React Native version

0.74.5

### Platforms

Android

### JavaScript runtime

None

### Workflow

Expo managed workflow

### Architecture

None

### Build type

Debug mode

### Device

Real device

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

This PR fixes issue in which `Hover` gesture blocks mouse wheel scroll. At first I thought that we should mark `Hover` as simultaneous with `ScrollView` (or to be more precise, `NativeViewGestureHandler` that wraps `ScrollView`), but it turned out that it was not the case. Instead of working simultaneous with `ScrollView`, we have to set this relation with `RootViewGestureHandler`.

Fixes #3064 

## Test plan

<details>
<summary>Tested on code from issue</summary>

```tsx
import {
  Text,
  SafeAreaView,
  StyleSheet,
  StatusBar,
  Pressable,
} from 'react-native';
import {
  GestureHandlerRootView,
  ScrollView,
  Gesture,
  GestureDetector,
} from 'react-native-gesture-handler';
import { useSharedValue } from 'react-native-reanimated';

export default function App() {
  return (
    <GestureHandlerRootView style={{ flex: 1 }}>
      <SafeAreaView style={styles.container}>
        <StatusBar />
        <ScrollView>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>
          <Text style={{ height: 50, backgroundColor: 'red' }}>item</Text>

          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
          <Button title="Button1" />
        </ScrollView>
      </SafeAreaView>
    </GestureHandlerRootView>
  );
}

const Button = (props) => {
  const hovered = useSharedValue(false);
  const hover = Gesture.Hover()
    .onStart((e) => {
      console.log('hover start');
    })
    .onEnd((e) => {
      hovered.value = false;
      console.log('hover end');
    });

  return (
    <GestureDetector gesture={hover}>
      <Pressable {...props}>
        <Text>{props.title}</Text>
      </Pressable>
    </GestureDetector>
  );
};
const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
    padding: 8,
  },
});

```

</details>

### CODE REVIEW

File: android/src/main/java/com/swmansion/gesturehandler/core/HoverGestureHandler.kt [hunk 1]
```diff
@@ -70,6 +71,10 @@ class HoverGestureHandler : GestureHandler<HoverGestureHandler>() {
       return true
     }
 
+    if (handler is RNGestureHandlerRootHelper.RootViewGestureHandler) {
```
Comment (m-bert) [inline android/src/main/java/com/swmansion/gesturehandler/core/HoverGestureHandler.kt:74]: We can also specify that `pointerType` has to be `mouse`, but I haven't found any issue with `stylus`
```suggestion
    if (handler is RNGestureHandlerRootHelper.RootViewGestureHandler && pointerType == POINTER_TYPE_MOUSE) {
```

**Comment by proohit** [comment]
I can confirm this fix works for my specific case.

**Review by j-piasecki — APPROVED** [review]
