### PR TITLE
Fix android ripple color bug on fabric

### LINKED ISSUE #3246: [Pressable] android_ripple / color doesn't work correctly
### Description

on `Pressable` android_ripple={color: XXX} doesn't work correctly.

Here are issues:
- when user configure the  android_ripple={color: "#FF0000"} => the ripple color is grey. What ever the configured color is, the color ripple color is always grey (should be red with this sample)
- when user configure the  android_ripple={color: "#FFFFFF4F"} (With transparency) => the ripple color is blue. depending of transparency level, the color is sometimes grey ...
- I have also notice that a fast refresh doesn't refresh correctly the ripple color. (maybe it can help to identify the issue, or at least don't fall in that trap)

I checked with default react native `Pressable` these 3 use cases works fine.

### Steps to reproduce

Just define a Pressable with android_ripple={{color}}

```JS
<Pressable onPress={() => console.log('onPress')} android_ripple={{color: '#FF0000'}}>
         <Text>'Hello World'</Text>
</Pressable>
```

### Snack or a link to a repository

https://github.com/freeboub/bug-react-native-gesture-handler-android-ripple-color

### Gesture Handler version

2.21.2

### React Native version

0.76.2

### Platforms

Android

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

Android emulator

### Device model

reproduced on all android devices

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by latekvo**
## Description

Android ripple currently does not work on `Fabric`, as all values passed to `RawButton` and it's inheritors are passed through `processColor`, which is crucial on `Paper`, and broken on `Fabric`.

This PR disables usage of `processColor`, when running on `Fabric`.

Note: `isFabric` cannot be moved out of the body of the `Pressable`, as it likely won't be initialised before the `Pressable` starts being rendered. More details [here](https://github.com/software-mansion/react-native-gesture-handler/blob/b3d8fd91dca195267bdc33aa20fd6f5cd37d7fe2/src/utils.ts#L47).

Fixes #3246
Fixes #3312
Supersedes #3250
Likely could add a workaround for https://github.com/software-mansion/react-native-reanimated/issues/6935

## Test plan

<details>
<summary>
Collapsed test code
</summary>

```tsx
import React from 'react';
import { Pressable as RNPressable, StyleSheet, Text } from 'react-native';
import {
  BaseButton,
  GestureHandlerRootView,
  RectButton,
  Pressable,
} from 'react-native-gesture-handler';

const App = () => {
  return (
    <GestureHandlerRootView>
      <RectButton style={styles.wrapperCustom} rippleColor={'blue'}>
        <Text style={styles.text}>RectButton</Text>
      </RectButton>
      <BaseButton style={styles.wrapperCustom} rippleColor={'blue'}>
        <Text style={styles.text}>BaseButton</Text>
      </BaseButton>
      <Pressable
        style={styles.wrapperCustom}
        android_ripple={{ color: 'blue' }}>
        {({ pressed }) => (
          <Text style={styles.text}>
            {pressed ? 'Pressed!' : 'Pressable from react-native'}
          </Text>
        )}
      </Pressable>
      <RNPressable
        style={styles.wrapperCustom}
        android_ripple={{ color: 'blue' }}>
        {({ pressed }) => (
          <Text style={styles.text}>
            {pressed ? 'Pressed!' : 'Pressable from react-native'}
          </Text>
        )}
      </RNPressable>
      <Pressable
        style={styles.wrapperCustom}
        android_ripple={{ color: '#00f' }}>
        {({ pressed }) => (
          <Text style={styles.text}>
            {pressed ? 'Pressed!' : 'Pressable from react-native'}
          </Text>
        )}
      </Pressable>
      <RNPressable
        style={styles.wrapperCustom}
        android_ripple={{ color: '#00f' }}>
        {({ pressed }) => (
          <Text style={styles.text}>
            {pressed ? 'Pressed!' : 'Pressable from react-native'}
          </Text>
        )}
      </RNPressable>
    </GestureHandlerRootView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    gap: 16,
    padding: 16,
  },
  text: {
    fontSize: 32,
  },
  wrapperCustom: {
    borderRadius: 8,
    padding: 6,
    flex: 1,
    backgroundColor: 'papayawhip',
    borderColor: 'red',
    borderWidth: 2,
  },
  logBox: {
    flex: 1,
    padding: 20,
    margin: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#f0f0f0',
    backgroundColor: '#f9f9f9',
  },
});

export default App;

```

</details>

### CODE REVIEW

File: src/components/Pressable/Pressable.tsx [hunk 1]
```diff
@@ -380,6 +378,18 @@ export default function Pressable(props: PressableProps) {
       ? children({ pressed: pressedState })
       : children;
 
+  const defaultRippleColor = useMemo(
```
Comment (freeboub) [inline src/components/Pressable/Pressable.tsx:381]: I think both memo can be merged into only 1 ..

Comment (latekvo) [reply src/components/Pressable/Pressable.tsx]: You're right, fixed in [a9d2031](https://github.com/software-mansion/react-native-gesture-handler/pull/3369/commits/a9d203156e759bf5fd8af644f0609b5821a5236a)

File: src/components/Pressable/Pressable.tsx [hunk 2]
```diff
@@ -380,6 +378,14 @@ export default function Pressable(props: PressableProps) {
       ? children({ pressed: pressedState })
       : children;
 
+  const rippleColor = useMemo(() => {
+    const defaultRippleColor = android_ripple ? undefined : 'transparent';
+    const unprocessedRippleColor = android_ripple?.color ?? defaultRippleColor;
```
Comment (m-bert) [inline src/components/Pressable/Pressable.tsx:383]: Shouldn't it be 

```jsx
const unprocessedRippleColor = android_ripple?.color ?? 'transparent';
```
?

I don't really see the point of `defaultRippleColor` in that case.

Comment (latekvo) [reply src/components/Pressable/Pressable.tsx:383]: `defaultRippleColor` is required to properly replicate the behaviour of RN `Pressable`.
When `android_ripple` is set, but the `color` field is not provided, we want to set `color` to `undefined`, so that it uses the default system value (whiteish opaque).
When `android_ripple` is not set, we want to remove the ripple altogether, which is done via `'transparent'`.

File: src/components/GestureButtons.tsx [hunk 3]
```diff
@@ -122,10 +123,14 @@ class InnerBaseButton extends React.Component<BaseButtonWithRefProps> {
   render() {
     const { rippleColor, style, ...rest } = this.props;
 
+    const processedRippleColor = isFabric()
```
Comment (m-bert) [inline src/components/GestureButtons.tsx:126]: What about `maybeProcessedRippleColor`?

Comment (m-bert) [reply src/components/GestureButtons.tsx:126]: Also, why don't we memoize value of `isFabric` instead of calling this everytime?

Comment (latekvo) [reply src/components/GestureButtons.tsx:126]: >What about maybeProcessedRippleColor?

Not a big fan of that name, the word `processed` already allows for lack of change.
But I agree that `processed` may be confusing due to `processColor()` function.
Is it ok if instead, I do the following?
`rippleColor` -> `unprocessedRippleColor`
`processedRippleColor` -> `rippleColor`

>Also, why don't we memoize value of isFabric instead of calling this everytime?

Sure, done in [ff48533](https://github.com/software-mansion/react-native-gesture-handler/pull/3369/commits/ff48533eacbf8641c7005744fbf12e6d89dc01a5)

Comment (m-bert) [reply src/components/GestureButtons.tsx:126]: > Sure, done in [ff48533](https://github.com/software-mansion/react-native-gesture-handler/pull/3369/commits/ff48533eacbf8641c7005744fbf12e6d89dc01a5)

Not exactly what I meant. I thought about storing it in a variable. Now we still call function in each render.

> Maybe this will do better:
rippleColor -> unprocessedRippleColor
processedRippleColor -> rippleColor

Looks good 👍

Comment (latekvo) [reply src/components/GestureButtons.tsx:126]: >Not exactly what I meant. I thought about storing it in a variable. Now we still call function in each render.

Can't do that, `isFabric()` will return incorrect data outside of the function component, as the value it reads will not be initialised before the first render.

Comment (latekvo) [reply src/components/GestureButtons.tsx]: > Looks good 👍 

Done in [2513b9e](https://github.com/software-mansion/react-native-gesture-handler/pull/3369/commits/2513b9e5bc1a71d974d4b0c5fbd52d2985676013)

**Review by m-bert — APPROVED** [review]
Looks ok 👍 

What about using the same `IS_FABRIC` trick in `Pressable`? 😅

**Comment by latekvo** [comment]
> What about using the same IS_FABRIC trick in Pressable?

Done in [f8b2de5](https://github.com/software-mansion/react-native-gesture-handler/pull/3369/commits/f8b2de56030319877a74b96d5260cd235d867aa2)

**Review by m-bert — APPROVED** [review]
