### PR TITLE
Address compilation warnings

### LINKED ISSUE #2460: Version 2.9.0 using deprecated Java features ("Deprecated in Java")
### Description

A lot of warnings appear during build which is currently polluting the build output.

Adding all warnings for people who search with partial logs for the same problem.

```
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 31): Parameter 'event' is never used
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt: (7, 41): Parameter 'reactApplicationContext' is never used
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/core/GestureHandler.kt: (755, 11): Name shadowed: size
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (9, 51): Unreachable code
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerEnabledRootView.kt: (10, 80): Unreachable code
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (77, 18): 'onChildStartedNativeGesture(MotionEvent!): Unit' is deprecated. Deprecated in Java
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (82, 42): Parameter 'disallowIntercept' is never used
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt: (114, 28): Parameter 'viewTag' is never used
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (7, 44): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (14, 11): 'init(Int): Unit' is deprecated. Deprecated in Java
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (30, 42): 'RCTEventEmitter' is deprecated. Deprecated in Java
w: /Users/andras.toth/projects/GestureHandlerDeprecatedWarnings/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerTouchEvent.kt: (31, 21): 'receiveEvent(Int, String!, WritableMap?): Unit' is deprecated. Deprecated in Java
```

### Steps to reproduce

1. Run to get the latest virgin `react-native` `npx react-native init GestureHandlerDeprecatedWarnings`
2. Run `yarn add react-native-gesture-handler`
3. Run `npm run android`

Results:
The following warnings.

### Snack or a link to a repository

https://github.com/latobibor/react-native-gesture-handler-build-warnings-repro

### Gesture Handler version

2.9.0

### React Native version

0.71.7, 0.69.9

### Platforms

Android

### JavaScript runtime

None

### Workflow

React Native (without Expo)

### Architecture

None

### Build type

Debug mode

### Device

Android emulator

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

It turns out that our code uses some deprecated functions. Also there were few more warnings, such as shadowed name or unused variables.

Some of included changes require digging into `react-native` source code to find alternative approach.

Fixes #2460 

## `dispatch` method

Based on @kkafar research in [screens](https://github.com/software-mansion/react-native-screens/pull/1867), I've replaced `dispatch` method with `getEventData`.

- [Here](https://github.com/facebook/react-native/blob/e2ef6b98a061508bdd70a4c2747fe061c49b5c39/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/uimanager/events/Event.java#L154-L168) you can find how `dispatch` looks like in the source code. 
- [Here](https://github.com/facebook/react-native/commit/72d0ddc16f2f631003c3486e0a59e50c145ec613#diff-afc6f25f459dcf1e24a012e16862c869aa04b0de5795171efe14b7a88be08e64) you can see example change in react-native

## Test plan

Tested that our example apps (paper and fabric) work as expected.

### CODE REVIEW

**Comment by jacksonlevine** [comment]
Can someone merge this, for Christ?

File: android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt [hunk 1]
```diff
@@ -78,12 +78,14 @@ class RNGestureHandlerRootHelper(private val context: ReactContext, wrappedView:
         action = MotionEvent.ACTION_CANCEL
       }
       if (rootView is RootView) {
-        rootView.onChildStartedNativeGesture(event)
+        rootView.onChildStartedNativeGesture(this.view, event)
```
Comment (m-bert) [inline android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt:81]: I'm not quite sure what should be passed here. Deprecated method calls this one with `null`, maybe we could also do that?

File: android/src/main/java/com/swmansion/gesturehandler/RNGestureHandlerPackage.kt [hunk 2]
```diff
@@ -71,7 +71,7 @@ class RNGestureHandlerPackage : TurboReactPackage(), ViewManagerOnDemandReactPac
             RNGestureHandlerModule::class.java.name,
             reactModule.canOverrideExistingModule,
             reactModule.needsEagerInit,
-            reactModule.hasConstants,
+            true, // Has constants is hardcoded to return true, so replacing it with `true` changes nothing.
```
Comment (m-bert) [inline android/src/main/java/com/swmansion/gesturehandler/RNGestureHandlerPackage.kt:74]: While leaving this line still leads to deprecation warning during build phase, we decided to leave that as it is, because removing this parameter leads to compilation errors on lower RN versions.

File: android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt (hunk 1 above)
Comment (j-piasecki) [reply android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt:81]: Ideally, I think we should pass a view of the activating gesture but I don't think we can access it here. I guess passing the root view is ok though, since we are certain that the view is its child.

File: android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt [hunk 3]
```diff
@@ -4,6 +4,8 @@ import com.facebook.react.bridge.ReactContext
 import com.facebook.react.uimanager.events.Event
 
 class ReanimatedEventDispatcher {
+  @Suppress("UNUSED_PARAMETER", "COMMENT_IN_SUPPRESSION")
+  // These parameters may be useful in the future
```
[the remark this answers is not in the document]
Comment (m-bert) [reply android/noreanimated/src/main/java/com/swmansion/gesturehandler/ReanimatedEventDispatcher.kt]: Changed in [b88fa75](https://github.com/software-mansion/react-native-gesture-handler/pull/2597/commits/b88fa75456f2333c65fd30d232fd0832c47fdb3e).

File: android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt [hunk 4]
```diff
@@ -78,12 +78,14 @@ class RNGestureHandlerRootHelper(private val context: ReactContext, wrappedView:
...
       if (rootView is RootView) {
-        rootView.onChildStartedNativeGesture(event)
+        rootView.onChildStartedNativeGesture(rootView, event)
       }
       event.recycle()
     }
   }
 
+  @Suppress("UNUSED_PARAMETER", "COMMENT_IN_SUPPRESSION")
+  // This parameter may be useful in the future
```
[the remark this answers is not in the document]
Comment (m-bert) [reply android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerRootHelper.kt]: According to our discussion I've removed it in [216dd69](https://github.com/software-mansion/react-native-gesture-handler/pull/2597/commits/216dd698665e98cdbc03d937d63132e01f5419dc).
