### PR TITLE
Remove lodash

### LINKED ISSUE #2613: Remove lodash
### Description

As far as I can tell lodash is used [once](https://github.com/software-mansion/react-native-gesture-handler/blob/a9272cf2471bd869a3c81e13fa114ecfea3cc835/src/handlers/createHandler.tsx#L391C13-L391C14) anywhere in the repo and could either be replaced with [lodash.isEqual](https://www.npmjs.com/package/lodash.isequal) or native JS.

### Steps to reproduce

N/A

### Snack or a link to a repository

https://github.com/software-mansion/react-native-gesture-handler/blob/a9272cf2471bd869a3c81e13fa114ecfea3cc835/src/handlers/createHandler.tsx#L391C13-L391C14

### Gesture Handler version

2.13.1

### React Native version

N/A

### Platforms

Web

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

None

### Device model

_No response_

### Acknowledgements

Yes

### PR DESCRIPTION
**Pull request by m-bert**
## Description

Since `lodash` is used only in one place in our codebase, we can simply replace it with our own implementation on `deepEqual`.

Closes #2613 

## Test plan

Run example apps.

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -59,3 +59,33 @@ export function isRemoteDebuggingEnabled(): boolean {
...
+    return true;
+  }
+
+  if (
+    typeof obj1 !== 'object' ||
+    typeof obj2 !== 'object' ||
+    obj1 === null ||
+    obj2 === null
+  ) {
+    return obj1 === obj2;
```
Comment (j-piasecki) [inline src/utils.ts:74]: This branch always returns `false`, no?

```suggestion
    return false;
```

Comment (m-bert) [reply src/utils.ts:74]: I'm pretty sure you're right.

**Review by j-piasecki — APPROVED** [review]
I'm pretty sure this won't work with cyclical references. We don't really need that at the moment since this is only used to compare gesture configs, but it would be nice to add a comment about that in case it's used somewhere else in the future.
